title: Linux Factory
email: tobetter@gmail.com
description: >-
  Linux Factory Documentation Site
baseurl: ""
url: "https://docs.linuxfactory.or.kr"

#theme: jekyll-theme-primer
remote_theme: carlosperate/jekyll-theme-rtd

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
